### ISSUE TITLE
Add 'tag_on_failure' property

### ISSUE THREAD

**Issue by hartfordfive** [logstash-plugins/logstash-filter-json#20]
It would be great if this filter could optionally add a custom tag upon failure, such as the grok or date filter.  This would be extremely useful in a multi-tenancy environment where the Logstash instance is processing many different json objects as it would potentially allow you to at least isolate which json filter failed, which could allow you to isolate the specific tenant.

**Comment by ph** [comment]
fixed in 2.0.4
